### ISSUE TITLE
Fix music player

### ISSUE THREAD

**Issue by naterchrdsn** [naterchrdsn/GReYBot#35]
errors out:

```
C:\DEV\GReYBot\node_modules\discord.js\src\client\voice\opus\OpusEngineList.js:23
  throw new Error('Couldn\'t find an Opus engine.');
  ^

Error: Couldn't find an Opus engine.
    at Object.exports.fetch (C:\DEV\GReYBot\node_modules\discord.js\src\client\v
oice\opus\OpusEngineList.js:23:9)
    at AudioPlayer (C:\DEV\GReYBot\node_modules\discord.js\src\client\voice\play
er\AudioPlayer.js:20:37)
    at VoiceConnection (C:\DEV\GReYBot\node_modules\discord.js\src\client\voice\
VoiceConnection.js:58:19)
    at PendingVoiceConnection.upgrade (C:\DEV\GReYBot\node_modules\discord.js\sr
c\client\voice\ClientVoiceManager.js:241:12)
    at PendingVoiceConnection.pass (C:\DEV\GReYBot\node_modules\discord.js\src\c
lient\voice\ClientVoiceManager.js:220:28)
    at PendingVoiceConnection.checkReady (C:\DEV\GReYBot\node_modules\discord.js
\src\client\voice\ClientVoiceManager.js:151:12)
    at PendingVoiceConnection.setTokenAndEndpoint (C:\DEV\GReYBot\node_modules\d
iscord.js\src\client\voice\ClientVoiceManager.js:192:10)
    at ClientVoiceManager.onVoiceServer (C:\DEV\GReYBot\node_modules\discord.js\
src\client\voice\ClientVoiceManager.js:36:74)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at VoiceServerUpdate.handle (C:\DEV\GReYBot\node_modules\discord.js\src\clie
nt\websocket\packets\handlers\VoiceServerUpdate.js:15:12)
    at WebSocketPacketManager.handle (C:\DEV\GReYBot\node_modules\discord.js\src
\client\websocket\packets\WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (C:\DEV\GReYBot\node_modules\discord.js\src
\client\websocket\WebSocketManager.js:273:31)
    at WebSocket.onMessage (C:\DEV\GReYBot\node_modules\ws\lib\WebSocket.js:442:
14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (C:\DEV\GReYBot\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\DEV\GReYBot\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\DEV\GReYBot\node_modules\ws\lib\Receiver.js:
371:5)
    at C:\DEV\GReYBot\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\DEV\GReYBot\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.finish (C:\DEV\GReYBot\node_modules\ws\lib\Receiver.js:541:12)
```

**Comment by develogix** [comment]
I think this is a dependency issue; probably just need to add the correct packages to `/package.json`.
